"""user_role tables

Revision ID: 152d32f7591b
Revises: d2fe1d55834f
Create Date: 2020-04-27 08:26:06.510128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152d32f7591b'
down_revision = 'd2fe1d55834f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    # ### end Alembic commands ###
